server:
  port: 8181

spring:
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0
kbz:
  url: "https://www.kbzbank.com/en/"

aya:
  url: "https://www.ayabank.com/en_US/"

yoma:
  url: "https://yomabank.com/mm/business/rates"

uab:
  url: "https://www.uab.com.mm/"

cb:
  url: "https://www.cbbank.com.mm/en"

agd:
  url: "https://www.agdbank.com/"
